// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nritruihtpakghjftxvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yaXRydWlodHBha2doamZ0eHZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4OTU0NTUsImV4cCI6MjA3MTQ3MTQ1NX0.ZYXrlY3VIRotZVjNyJMX4iwyCGndjwwQyxmXvtKi3gs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});